### PR TITLE
conf: sdk_210209_defconfig: enable SENSORS_SFCTMP

### PR DESCRIPTION
**Pull request by mike-scott**
The following patch added support for an SFC tmperature sensor:
Patch: https://github.com/starfive-tech/beagle_kernel_5.10/commit/b6b0e571705ba82560f604780646d24993aa56c0

However, the config needs to be enabled or the driver won't load.

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by mike-scott** [comment]
@pdp7 NOTE: This driver requires a DTS node and I'm not seeing that anywhere.  So maybe this isn't ready to be enabled.

**Comment by RobertCNelson** [comment]
Ugh, the CI BuildBot ran out of space, swapping Hard Drives, should kick it again shortly. ;)

**Comment by pdp7** [comment]
@mike-scott thank you

@MichaelZhuxx @tekkamanninja:
I have tested this and it works when using DTS change in this PR https://github.com/starfive-tech/sft-riscv-uboot/pull/4
```
# dmesg |grep sfc_temp
[    3.770961] sfc_temp_sensor 124a0000.tmpsensor: probe
# cat /sys/bus/platform/drivers/sfc_temp_sensor/124a0000.tmpsensor/temp1_input 
40.84
```

**Comment by MichaelZhuxx** [comment]
@mike-scott thanks a lot

**Pull request merged**
